theme: jekyll-theme-minimal
title: "Ominous Engine"
description: "Ominous Engine is a mod for Friday Night Funkin', including a full engine rework, replays, and more."
show_downloads: true
replace_index_with: "https://cors-thing.puyo.workers.dev/master/"
logo: "https://github.com/MasterOminousDev/Ominous-Engine/raw/stable/OminousEngineLogo.png"
url: "https://MasterOminousDev.github.io/Ominous-Engine/"
